name: CI

on:
  push:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v6

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [commitlint]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Fetch Tags
        run: git fetch --tags

      - name: Create Temp Version File
        run: "git tag --sort=version:refname --list 'v*' | tail -n 1 | jq -R 'ltrimstr(\"v\") | {\"version\": .}' > version.json"

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          git-branch: main
          skip-git-pull: true
          output-file: false
          version-file: version.json
          preset: conventionalcommits
          skip-on-empty: false
          git-push: false

      - name: Run Build
        run: ./gradlew build

      - name: Upload Gradle Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          if-no-files-found: error

  typescript-client:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [build]
    steps:
      - name: Download Gradle Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install TypeScript Client Dependencies
        run: npm install
        working-directory: build/smithyprojections/CodyModel/source/typescript-client-codegen/

      - name: Build TypeScript Client
        run: npm run build
        working-directory: build/smithyprojections/CodyModel/source/typescript-client-codegen/

      - name: Publish TypeScript Client
        run: npm publish
        working-directory: build/smithyprojections/CodyModel/source/typescript-client-codegen/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  typescript-server:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [build]
    steps:
      - name: Download Gradle Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install TypeScript Server Dependencies
        run: npm install
        working-directory: build/smithyprojections/CodyModel/source/typescript-server-codegen/

      - name: Build TypeScript Server
        run: npm run build
        working-directory: build/smithyprojections/CodyModel/source/typescript-server-codegen/

      - name: Publish TypeScript Server
        run: npm publish
        working-directory: build/smithyprojections/CodyModel/source/typescript-server-codegen/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [typescript-client, typescript-server]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --tags

      - name: Create Temp Version File
        run: "git tag --sort=version:refname --list 'v*' | tail -n 1 | jq -R 'ltrimstr(\"v\") | {\"version\": .}' > version.json"

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          git-branch: main
          skip-git-pull: true
          output-file: false
          version-file: version.json
          preset: conventionalcommits
          skip-on-empty: false
          git-push: false

      - name: Push Tags
        run: git push origin --tags