name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          if-no-files-found: error

  typescript-client:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install Client Dependencies
        run: npm install
        working-directory: build/smithyprojections/CodyModel/source/typescript-client-codegen/

      - name: Build Client
        run: npm run build
        working-directory: build/smithyprojections/CodyModel/source/typescript-client-codegen/

      - name: Publish Client
        run: npm publish
        working-directory: build/smithyprojections/CodyModel/source/typescript-client-codegen/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  typescript-server:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install Server Dependencies
        run: npm install
        working-directory: build/smithyprojections/CodyModel/source/typescript-server-codegen/

      - name: Build Server
        run: npm run build
        working-directory: build/smithyprojections/CodyModel/source/typescript-server-codegen/

      - name: Publish Server
        run: npm publish
        working-directory: build/smithyprojections/CodyModel/source/typescript-server-codegen/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
