name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build Smithy
      run: ./gradlew smithyBuild

  dependabot:
      permissions: write-all
      runs-on: ubuntu-latest
      if: github.actor == 'dependabot[bot]'
      needs: [build]
      steps:
        - name: Dependabot metadata
          id: metadata
          uses: dependabot/fetch-metadata@v2
          with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"
        - name: Enable auto-merge for Dependabot PRs
          run: gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GH_TOKEN: ${{secrets.GITHUB_TOKEN}}